[config]
schemaVersion = "0.0.1"


[package]
namespace = "jakzo"
name = "SpeedrunTimer"
versionNumber = "1.8.1"
description = "Timer for Bonelab speedruns."
websiteUrl = "https://github.com/jakzo/SlzMods/tree/main/projects/Bonelab/SpeedrunTimer"
containsNsfwContent = false

[package.dependencies]


[build]
icon = "./icon.png"
readme = "./generated-README.md"
outdir = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "bonelab" ]

[publish.categories]
bonelab = [ "code-mods" ]

