[config]
schemaVersion = "0.0.1"


[package]
namespace = "jakzo"
name = "Colliders"
versionNumber = "0.0.0"
description = "Makes colliders visible."
websiteUrl = "https://github.com/jakzo/SlzSpeedrunTools/tree/main/projects/Bonelab/Colliders"
containsNsfwContent = false

[package.dependencies]


[build]
icon = "./icon.png"
readme = "./generated-README.md"
outdir = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "bonelab" ]

[publish.categories]
bonelab = [ "code-mods" ]

