[config]
schemaVersion = "0.0.1"


[package]
namespace = "jakzo"
name = "SpeedrunTools"
versionNumber = "2.5.2"
description = "Utilities for Boneworks speedrunning."
websiteUrl = "https://github.com/jakzo/SlzMods/tree/main/projects/Boneworks/SpeedrunTools"
containsNsfwContent = false

[package.dependencies]


[build]
icon = "./icon.png"
readme = "./generated-README.md"
outdir = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "boneworks" ]

[publish.categories]
boneworks = [ "code-mods" ]

